[relaychain]
default_command = "polkadot-sdk/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "polkadot-local"
#chain_spec_command = "runtimes/target/release/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
chain_spec_path = "polkadot-local-patched.json"

  [[relaychain.nodes]]
  name = "Relay1"
  validator = true

  [[relaychain.nodes]]
  name = "Relay2"
  validator = true

[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "asset-hub-polkadot-local"
#chain_spec_command = "runtimes/target/release/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
chain_spec_path = "ah-local.json"

  [[parachains.collators]]
  name = "AssetHub"
  command = "polkadot-sdk/target/release/polkadot-parachain"
  args = ["-lparachain=debug"]
