[relaychain]
default_command = "../polkadot-sdk/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain_spec_path = "relaychain-spec.json"

  [[relaychain.nodes]]
  name = "Relay1"
  validator = true

  [[relaychain.nodes]]
  name = "Relay2"
  validator = true

[[parachains]]
id = 1000
chain_spec_path = "assethub-spec.json"
add_to_genesis = true
cumulus_based = true

  [[parachains.collators]]
  name = "AssetHub"
  command = "../polkadot-sdk/target/release/polkadot-parachain"
  args = ["-lparachain=debug"]
